### ISSUE TITLE
Bug "no data yet"

### ISSUE THREAD

**Issue by bridget75** [Jaspero/jms#412] opened 2022-10-05 08:50 UTC
![image](https://user-images.githubusercontent.com/93909566/194020431-62273f61-1d21-4899-ac10-d1ef190160d7.png)

flow:  - opened CMS, selected pages, go back to the dashboard and selected again pages and saw the bug

**Comment by AntonioStipic** [comment] 2022-10-05 09:34
Great catch!

Cannot reproduce on JMS main, seems to be already fixed via e1acfc0f
BioViva needs to be updated to latest version or minimal v5.31.0 to resolve this issue.

**Closed by AntonioStipic** 2022-10-05 09:34 UTC
Labels: bug
